/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings.route'
import { Route as DashboardProfileRouteRouteImport } from './routes/dashboard/profile.route'
import { Route as DashboardModelsRouteRouteImport } from './routes/dashboard/models.route'
import { Route as DashboardLogsRouteRouteImport } from './routes/dashboard/logs.route'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRouteRoute = DashboardProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelsRouteRoute = DashboardModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRouteRoute = DashboardLogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/logs': typeof DashboardLogsRouteRoute
  '/dashboard/models': typeof DashboardModelsRouteRoute
  '/dashboard/profile': typeof DashboardProfileRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/logs': typeof DashboardLogsRouteRoute
  '/dashboard/models': typeof DashboardModelsRouteRoute
  '/dashboard/profile': typeof DashboardProfileRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/logs': typeof DashboardLogsRouteRoute
  '/dashboard/models': typeof DashboardModelsRouteRoute
  '/dashboard/profile': typeof DashboardProfileRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/logs'
    | '/dashboard/models'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/proxy/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/logs'
    | '/dashboard/models'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/proxy/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/logs'
    | '/dashboard/models'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/proxy/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/models': {
      id: '/dashboard/models'
      path: '/models'
      fullPath: '/dashboard/models'
      preLoaderRoute: typeof DashboardModelsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardLogsRouteRoute: typeof DashboardLogsRouteRoute
  DashboardModelsRouteRoute: typeof DashboardModelsRouteRoute
  DashboardProfileRouteRoute: typeof DashboardProfileRouteRoute
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLogsRouteRoute: DashboardLogsRouteRoute,
  DashboardModelsRouteRoute: DashboardModelsRouteRoute,
  DashboardProfileRouteRoute: DashboardProfileRouteRoute,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
